{
    'name': 'Project Custom',
    'version': '1.0',
    'author': 'Advanced Biz Consulting(ABC)',
    'website': 'https://www.abc.mr',
    'category': 'Services',
    'summary': 'Custom module to manage strategies and align strategic projects with the annual projects',
    # 'depends': ['base', 'project', 'hr', 'strategy', 'account_accountant', 'account_budget', 'analytic'],
    # 'depends': ['base', 'project', 'hr', 'strategy', 'website', 'account_budget_oca'],
    # 'depends': ['base', 'project', 'hr', 'strategy', 'account_budget_oca','contacts','calendar','mail','abc_exp_besoin','web_view_leaflet_map'],
    'depends': ['project', 'hr', 'account_budget_oca','contacts'],
    'data': [
        'data/tags.xml',
        'security/hr_groups.xml',
        'security/ir.model.access.csv',
        'security/autorite_security.xml',
        'data/qr_data.xml',
        'data/project_data.xml',
        'data/project_mail_tempate.xml',
        'data/project_qr_code_template.xml',
        'data/autorite_document_type.xml',
        'data/passation_status.xml',

        'views/project_portal_templates.xml',
        'views/webclient_templates.xml',

        # 'views/project_task_views.xml',
        'views/api_project_views.xml',
        'views/project_feedback_views.xml',
        'views/project_stop_station_views.xml',
        'views/project_geolocation_views.xml',
        'views/res_partner_appraisal_views.xml',
        'views/project_project_views.xml',
        'views/budget_lines.xml',
        'views/budget.xml',
        # 'views/realisation.xml',
        'views/account_analytic_line_views.xml',
        'views/project_avenant_view.xml',
        'views/menu_items.xml',
        'views/project_milestone_views.xml',
        'views/mail_tracking_custom.xml',
        'views/ir_attachment_custum.xml',
        'views/milestone_wizard.xml',
        'views/project_update_views.xml',
        'views/project_indicator_views.xml',

        #financial transaction views
        'views/project_proleme_view.xml',
        'views/res_partner_filter.xml',
        'views/filter_fileds.xml',
        'views/action_attributaire_views.xml',
        'views/action_autorite_contractante_view.xml',
        'views/action_commission_passation_view.xml',
        'views/res_partner_view.xml',
        'views/menus_contacts.xml',
        'views/autorite_views.xml',
        'wizard/wizard_planning_tag.xml',
        'views/tag_views.xml',
        'views/abc_exp_besoin_mission_projects_views.xml',
        'wizard/wizard_expression_view.xml',
        'wizard/project_share_wizard.xml',

        'views/post_control_views.xml',

        'reports/abc_exp_besoin_mission_projects_report.xml',
        'reports/abc_exp_besoin_mission_projects_template.xml',

    ],
    
    'assets': {
        'web.assets_backend': [
            # 'project_customization/static/src/css/progress_bar.css',
            'project_customization/static/src/js/welcome_message.js',
            'project_customization/static/src/js/progress_bar.js',
            'project_customization/static/src/js/progress_bar_no_arrounding.js',
            'project_customization/static/src/js/feedback_tree_button.js',
            'project_customization/static/src/js/feedback_kanban_button.js',
            'project_customization/static/src/xml/feedback_tree_button.xml',
            'project_customization/static/src/xml/feedback_kanban_button.xml',
        ],
        'web.qunit_suite_tests': [
            'analytic/static/tests/*.js',
        ],
    },
    'license': 'LGPL-3',
    'installable': True,
    'auto_install': False,
}
